apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: br-latest-tekton
    - name: url
      value: https://github.com/sandeep782/deploy-app-using-tekton-on-kubernetes.git
