apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image-from-source
spec:
  resources:
    - name: git-source
      type: git
    - name: url
      value: https://github.com/sandeep782/deploy-app-using-tekton-on-kubernetes.git
  params:
    - name: token
      description: git token
         
  steps:
    - name: hello
      image: golang # contains python
      env:
        - name: token
          value: $(params.token)
      command:
      - git
        
      args:
      - clone
      - https://sandeep782:$(params.token)@github.com/sandeep782/deploy-app-using-tekton-on-k8s.gi
          
      script: |
        #!/usr/bin/env bash
        pwd
        
        
        
#           git clone https://sandeep782:$token@github.com/sandeep782/deploy-app-using-tekton-on-k8s.git
         
          
#         image: ubuntu
#         command: ["echo"]
#         args: ["Hello"] 
#     - name: list-src
#       image: 'alpine:3.14'
#       command:
#         - ls
#       args:
#         - $(inputs.resources.url)
#     - name: build-and-push
#       image: gcr.io/kaniko-project/executor:latest
#       command:
#         - /kaniko/executor
#       args:
#         - '--context=$(inputs.resources.url)/$(inputs.params.pathToContext)/'
#         - '--dockerfile=$(inputs.params.pathToDockerfile)'
#         - '--destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)'
#         - "--verbosity=trace"
       
